In [1]:
import torch.nn as nn
import torch

In [4]:
embedding = nn.Embedding(10, 3)

# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])
embedding(input)

tensor([[[-0.5386,  0.4623, -0.2602],
         [ 0.8625,  1.0182, -1.2247],
         [-1.4371, -0.7975, -0.0684],
         [-1.7505, -1.1251,  0.3646]],

        [[-1.4371, -0.7975, -0.0684],
         [ 0.5315,  0.5203, -0.3134],
         [ 0.8625,  1.0182, -1.2247],
         [-1.0974, -0.0145,  0.4845]]], grad_fn=<EmbeddingBackward>)

In [5]:
# example with padding_idx
embedding = nn.Embedding(10, 3, padding_idx=9)
# a batch of 2 samples of 4 indices each
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])
embedding(input)

tensor([[[-1.0830,  0.2236,  0.8860],
         [ 0.4657,  0.4878,  0.5590],
         [-0.0152, -0.7465,  0.9950],
         [-0.7042,  0.4227,  0.3879]],

        [[-0.0152, -0.7465,  0.9950],
         [-0.7233, -0.3816,  0.9273],
         [ 0.4657,  0.4878,  0.5590],
         [ 0.0000,  0.0000,  0.0000]]], grad_fn=<EmbeddingBackward>)

nn.Embedding指定padding_idx，则padding_idx lookup出来的向量就全是0

In [6]:
# embedding矩阵的向量初始化
embedding.weight.data.uniform_(-0.25, 0.25)

tensor([[-0.0426, -0.2230, -0.1859],
        [ 0.2496,  0.2093, -0.2239],
        [-0.0552, -0.1697, -0.2333],
        [-0.1601, -0.0969,  0.0097],
        [-0.2098,  0.0576,  0.1600],
        [-0.0494,  0.0017,  0.1612],
        [ 0.0685,  0.1009, -0.0825],
        [ 0.2320, -0.1644,  0.1936],
        [ 0.1880,  0.1833, -0.1776],
        [ 0.2230, -0.1144, -0.2213]])