In [1]:
import torch

## torch.norm
求一个tensor的范数，默认是2范数

In [4]:
x = torch.tensor([1,2,3], dtype=torch.float32)
torch.norm(x)

tensor(3.7417)

## BN和LN

#### BN

In [22]:
import numpy as np
from torch import nn

def torch_bn_offical(x):
    """ 调用官方API
    """
    # BN统计B，H，W均值，剩C通道
    c = x.shape[1]
    # affine=False, 方便结果对比只做减均值除方差，不乘gamma加 beta
    bn = nn.BatchNorm2d(num_features=c, eps=0, affine=False, track_running_stats=False)
    official_bn = bn(x)
    return official_bn


def torch_bn_our(x):
    c = x.shape[1]
    mu = x.mean(dim=[0, 2, 3]).view(1, c, 1, 1)
    print(mu.size())
    std = x.std(dim=[0, 2, 3], unbiased=False).view(1, c, 1, 1)
    my_bn = (x - mu) / std
    return my_bn

In [24]:
x = torch.tensor([[1,1,1], [2,2,2], [3,3,3], [4,4,4]], dtype=torch.float32)
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])

In [25]:
torch.mean(x, dim=0)

tensor([2.5000, 2.5000, 2.5000])

In [13]:
torch.mean(x, dim=[0,1])

tensor(2.5000)

In [14]:
y = torch.rand((4, 6, 2,2))

In [16]:
torch.mean(y, dim=[0,2,3])

tensor([0.4618, 0.4533, 0.5194, 0.5103, 0.3937, 0.4380])

In [26]:
# test
print(torch_bn_offical(y))
print(torch_bn_our(y))

tensor([[[[-0.6662,  2.4058],
          [-0.8449, -1.0616]],

         [[ 1.2691, -1.3758],
          [-0.6908, -0.7311]],

         [[ 0.7464, -1.3606],
          [-1.7547, -0.6726]],

         [[ 1.0989,  1.1128],
          [-0.2165, -0.7294]],

         [[ 1.2964, -1.4783],
          [-0.4415,  1.1208]],

         [[-0.3025,  0.0591],
          [ 1.5023, -0.6072]]],


        [[[ 0.2389, -0.6292],
          [ 1.2919, -0.4920]],

         [[ 1.6049,  0.8935],
          [ 0.1705, -1.1388]],

         [[ 0.2058,  0.3032],
          [-1.0745, -0.0090]],

         [[-1.1947,  0.9580],
          [ 1.1324,  0.9466]],

         [[-1.6296,  0.2228],
          [-0.3425,  0.2579]],

         [[ 1.1628, -1.1664],
          [-1.2782,  1.4835]]],


        [[[ 1.4034, -1.1436],
          [-0.6492,  0.6979]],

         [[ 0.2550, -1.6606],
          [-0.3848,  1.2862]],

         [[-0.2011,  0.0447],
          [ 1.5068,  0.7889]],

         [[ 1.1059, -0.5781],
          [-0.9588, -0.0956]],

    

torch.Size([1, 6, 1, 1])


tensor([[[[-0.6662,  2.4058],
          [-0.8449, -1.0616]],

         [[ 1.2691, -1.3758],
          [-0.6908, -0.7311]],

         [[ 0.7464, -1.3606],
          [-1.7547, -0.6726]],

         [[ 1.0989,  1.1128],
          [-0.2165, -0.7294]],

         [[ 1.2964, -1.4783],
          [-0.4415,  1.1208]],

         [[-0.3025,  0.0591],
          [ 1.5023, -0.6072]]],


        [[[ 0.2389, -0.6292],
          [ 1.2919, -0.4920]],

         [[ 1.6049,  0.8935],
          [ 0.1705, -1.1388]],

         [[ 0.2058,  0.3032],
          [-1.0745, -0.0090]],

         [[-1.1947,  0.9580],
          [ 1.1324,  0.9466]],

         [[-1.6296,  0.2228],
          [-0.3425,  0.2579]],

         [[ 1.1628, -1.1664],
          [-1.2782,  1.4835]]],


        [[[ 1.4034, -1.1436],
          [-0.6492,  0.6979]],

         [[ 0.2550, -1.6606],
          [-0.3848,  1.2862]],

         [[-0.2011,  0.0447],
          [ 1.5068,  0.7889]],

         [[ 1.1059, -0.5781],
          [-0.9588, -0.0956]],

    

#### LN

In [28]:
def torch_ln_offical(x):
    """ 调用官方API
    """
    # afflne=False, 只做减均值除方差，不乘gamma加 beta
    layer_norm = nn.LayerNorm(normalized_shape=x.shape[1:], eps=0, elementwise_affine=False)
    official_ln = layer_norm(x)
    return official_ln


def torch_ln_our(x):
    b = x.shape[0]
    mu = x.mean(dim=[1, 2, 3]).view(b, 1, 1, 1)
    std = x.std(dim=[1, 2, 3], unbiased=False).view(b, 1, 1, 1)
    my_ln = (x - mu) / std
    return my_ln

In [29]:
z = torch.rand((4, 6, 2,2))

In [30]:
# test
print(torch_ln_offical(z))
print(torch_ln_our(z))

tensor([[[[ 1.0351,  0.8372],
          [-0.1234, -1.3442]],

         [[ 0.8443, -1.2238],
          [ 0.7800, -1.2791]],

         [[ 0.9719,  0.6339],
          [ 0.2897,  1.5540]],

         [[ 1.1893,  0.8428],
          [-1.0281,  0.9974]],

         [[-1.6397, -0.8868],
          [-0.8002, -1.5723]],

         [[-0.9091, -0.0252],
          [ 0.6995,  0.1568]]],


        [[[-1.6782, -0.2300],
          [-0.4100, -0.4686]],

         [[ 0.3576, -1.2818],
          [-1.3004,  0.3561]],

         [[ 0.4078,  0.4434],
          [-1.4889, -0.5424]],

         [[ 1.0645,  1.4128],
          [-1.7131,  0.0487]],

         [[ 1.1370, -0.3537],
          [ 1.2537,  0.7214]],

         [[ 0.1821,  1.8554],
          [-0.6621,  0.8889]]],


        [[[-0.5915,  1.0956],
          [ 0.0623,  0.6384]],

         [[-0.6585,  0.7993],
          [-1.3248, -1.2171]],

         [[ 1.1881, -1.2237],
          [ 1.2544, -0.9238]],

         [[-1.2183,  1.0247],
          [-0.4271,  0.8417]],

    

3
